export const FORMAT_MOMENT = {
    DATE_LONG: "YYYY-MM-DD",
    MONTH: "MM",
    YY: "YYYY",
    MM_YYYY: "MM/YYYY",
    DD_MM: "DD/MM",
    DD_MM_HH_mm: "DD/MM HH:mm",
    YYYY_MM_DD_SLASH: "YYYY/MM/DD",
    DATE_SLASH_LONG: "DD/MM/YYYY",
    DATE_SLASH_SHORT: "DD/MM/YY",
    DD_MM_YYYY: "DD-MM-YYYY",
    DATE_TIME_LONG: "YYYY-MM-DD HH:mm:ss",
    DATE_TIME_SHORT: "YYYY-MM-DD HH:mm",
    DATE_TIME_SLASH_LONG: "DD/MM/YYYY HH:mm:ss",
    DATE_TIME_SLASH_SHORT: "DD/MM/YYYY HH:mm",
    TIME_LONG: "HH:mm:ss",
    TIME_SHORT: "HH:mm",
    TIME_24H_SHORT: "HH:mm A",
    YYYY: "HH:mm",
    HH_MM_DD_MM_YY: "HH:mm DD-MM-YY",
};
