import { v4 as uuid } from "uuid";
export const data = [
    {
        id: uuid(),
        title: "Cắt",
        color: "#5770F7",
        icon: "/manufacture/presention-chart0.png",
        child: [
            {
                id: uuid(),
                bg: "#5770F7",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#5770F7",
            },
        ],
    },
    {
        id: uuid(),
        title: "Cắt",
        color: "#5770F7",
        icon: "/manufacture/presention-chart0.png",
        child: [
            {
                id: uuid(),
                bg: "#5770F7",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#5770F7",
            },
        ],
    },
    {
        id: uuid(),
        title: "Cắt",
        color: "#5770F7",
        icon: "/manufacture/presention-chart0.png",
        child: [
            {
                id: uuid(),
                bg: "#5770F7",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#5770F7",
            },
        ],
    },
    {
        id: uuid(),
        title: "Thêu",
        color: "#FF641C",
        icon: "/manufacture/presention-chart.png",
        child: [
            {
                bg: "#FF641C",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },

                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#FF641C",
            },
            {
                id: uuid(),
                bg: "#FF641C",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/no.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "",
                numberLeft: "",
                numberTitleRight: "",
                numberRight: "",
                manufacture: true,
                no: "Chưa sản xuất",
                colorNo: "#FF8F0D",
                color: "#FF641C",
            },
            {
                id: uuid(),
                bg: "#FF641C",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },

                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#FF641C",
            },
        ],
    },
    {
        id: uuid(),
        title: "May",
        color: "#F757CA",
        icon: "/manufacture/presention-chart3.png",
        child: [
            {
                id: uuid(),
                bg: "#F757CA",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#F757CA",
            },
            {
                id: uuid(),
                bg: "#F757CA",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#F757CA",
            },
            {
                id: uuid(),
                bg: "#F757CA",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#F757CA",
            },
        ],
    },
    {
        id: uuid(),
        title: "Bán thành phẩm",
        color: "#14B0FE",
        icon: "/manufacture/presention-chart4.png",
        child: [
            {
                id: uuid(),
                bg: "#14B0FE",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#14B0FE",
            },
            {
                id: uuid(),
                bg: "#14B0FE",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#14B0FE",
            },
            {
                id: uuid(),
                bg: "#14B0FE",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#14B0FE",
            },
            {
                id: uuid(),
                bg: "#14B0FE",
                order: "Đơn hàng SO-22072301",
                titeLeft: {
                    top: "Số lệnh SX chi tiết",
                    bottom: "LSXCT-22072301",
                },
                titleRight: {
                    top: "Số lượng cần sản xuất",
                    bottom: "12.098",
                },
                image: "/manufacture/Image.png",
                name: "Cổ áo",
                desription: "COAOTHUN",
                numberTitleLeft: "Số lượng đạt",
                numberLeft: "12.000",
                numberTitleRight: "Số lượng phế",
                numberRight: "120",
                manufacture: false,
                color: "#14B0FE",
            },
        ],
    },
];
